BookSeller/Models/Author.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookSeller.Models
{
    public class Author
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Profile Picture is required")]
        [Display(Name ="Profile Picture")]
        public string ProfilePictureURL { get; set; }

        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Full Name is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Full Name must be between 3 and 50 chars")]
        public string FullName { get; set; }

        [Display(Name = "Biography")]
        [Required(ErrorMessage = "Biography is required")]
        public string Bio { get; set; }
        [NotMapped]
        public IFormFile PictureFile { get; set; }
    }
}

BookSeller/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookSeller.Data;
using BookSeller.Models;
using System.Security.Policy;
using Microsoft.AspNetCore.Authorization;
using BookSeller.Data.Static;

namespace BookSeller.Controllers
{
    //[Authorize(Roles = UserRoles.Admin)]
    public class AuthorsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public AuthorsController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        //[AllowAnonymous]
        // GET: Authors
        public async Task<IActionResult> Index()
        {
              return View(await _context.Authors.ToListAsync());
        }
        [AllowAnonymous]
        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }
            ViewBag.bookAuthor = _context.Books.Where(n => n.AuthorId == author.Id);

            return View(author);
        }

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PictureFile,FullName,Bio")] Author author)
        {
            if (!ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(author.PictureFile.FileName);
                string extension = Path.GetExtension(author.PictureFile.FileName);
                fileName += DateTime.Now.ToString("ddMMyyyy") + extension;
                author.ProfilePictureURL = fileName;
                string path = Path.Combine(wwwRootPath + "/Img/Author", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await author.PictureFile.CopyToAsync(fileStream);
                }
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PictureFile,FullName,Bio")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(author.PictureFile.FileName);
                    string extension = Path.GetExtension(author.PictureFile.FileName);
                    fileName += DateTime.Now.ToString("ddMMyyyy") + extension;
                    author.ProfilePictureURL = fileName;
                    string path = Path.Combine(wwwRootPath + "/Img/Author", fileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await author.PictureFile.CopyToAsync(fileStream);
                    }
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Authors == null)
            {
                return Problem("Entity set 'AppDbContext.Authors'  is null.");
            }
            var author = await _context.Authors.FindAsync(id);
            if (author != null)
            {
                _context.Authors.Remove(author);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
          return _context.Authors.Any(e => e.Id == id);
        }
    }
}

BookSeller/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookSeller.Data;
using BookSeller.Models;
using Microsoft.AspNetCore.Hosting;
using NuGet.Protocol;
using Microsoft.AspNetCore.Authorization;
using BookSeller.Data.Static;

namespace BookSeller.Controllers
{
	[Authorize(Roles = UserRoles.Admin)]
	public class BooksController : Controller
	{
		private readonly AppDbContext _context;
		private readonly IWebHostEnvironment _webHostEnvironment;
		public BooksController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
		{
			_context = context;
			_webHostEnvironment = webHostEnvironment;
		}
		[AllowAnonymous]

		// GET: Books
		public async Task<IActionResult> Index()
		{
			TempData["Cate"] = 0;
			var appDbContext = _context.Books.Include(b => b.Author).Include(b => b.Publisher).Include(b => b.Category);
			return View(await appDbContext.ToListAsync());
		}
		[AllowAnonymous]

		public IActionResult Filter(string searchString)
		{
			var allBooks = from b in _context.Books.Include(b => b.Author).Include(b => b.Publisher).Include(b => b.Category) select b;
			if (!string.IsNullOrEmpty(searchString))
			{
				var filterBooks = allBooks.Where(s => s.Name.Contains(searchString) || s.Author.FullName.Contains(searchString)).ToList();
				if (filterBooks.Count == 0)
				{
					ViewBag.emty = "Không tìm thấy cuốn sách này";
				}
				return View("Index", filterBooks);
			}
			return View("Index", allBooks.ToList());
		}

		[AllowAnonymous]
		public IActionResult Category(int category)
		{
			var allBooks = from b in _context.Books.Include(b => b.Author).Include(b => b.Publisher).Include(b => b.Category) select b;
			var filterBooks = allBooks.Where(s => ((int)s.CategoryId) == category).ToList();
			if(filterBooks.Count == 0)
			{
				ViewBag.emtyCate = "Không có thể loại bạn vừa tìm";
			}
			TempData["Cate"] = category;
			return View("Index", filterBooks);
		}
		[AllowAnonymous]

		// GET: Books/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Books == null)
			{
				return NotFound();
			}

			var book = await _context.Books
				.Include(b => b.Author)
				.Include(b => b.Publisher)
				.Include(b => b.Category)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (book == null)
			{
				return NotFound();
			}
			var bookPublishers = _context.Books.Where(n => n.Id != book.Id).Where(n => n.AuthorId == book.AuthorId).Take(5);
			ViewBag.bookPublisher = bookPublishers.Count() != 0 ? bookPublishers : null;
			var bookAuthors = _context.Books.Where(n => n.Id != book.Id).Where(n => n.PublisherId == book.PublisherId).Take(5);
			ViewBag.bookAuthor = bookAuthors.Count() != 0 ? bookAuthors : null;
			var bookCates = _context.Books.Where(n => n.CategoryId == book.CategoryId).Where(n => n.Id != book.Id).Take(5);
			ViewBag.bookCate = bookCates.Count() != 0 ? bookCates : null;
			return View(book);
		}
		// GET: Books/Create
		public IActionResult Create()
		{
			ViewBag.AuthorId = new SelectList(_context.Authors.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.PublisherId = new SelectList(_context.Publishers.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.CategoryId = new SelectList(_context.Categories.OrderBy(n => n.Name).ToList(), "Id", "Name");
			return View();
		}

		// POST: Books/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,PictureFile,PublishingYear,CategoryId,AuthorId,PublisherId")] Book book)
		{
			if (!ModelState.IsValid)
			{
				string wwwRootPath = _webHostEnvironment.WebRootPath;
				string fileName = Path.GetFileNameWithoutExtension(book.PictureFile.FileName);
				string extension = Path.GetExtension(book.PictureFile.FileName);
				fileName += DateTime.Now.ToString("ddMMyyyy") + extension;
				book.ImageURL = fileName;
				string path = Path.Combine(wwwRootPath + "/Img/Book", fileName);
				using (var fileStream = new FileStream(path, FileMode.Create))
				{
					await book.PictureFile.CopyToAsync(fileStream);
				}
				_context.Add(book);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			ViewBag.AuthorId = new SelectList(_context.Authors.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.PublisherId = new SelectList(_context.Publishers.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.CategoryId = new SelectList(_context.Categories.OrderBy(n => n.Name).ToList(), "Id", "Name");
			return View(book);
		}

		// GET: Books/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Books == null)
			{
				return NotFound();
			}

			var book = await _context.Books.FindAsync(id);
			if (book == null)
			{
				return NotFound();
			}
			ViewBag.AuthorId = new SelectList(_context.Authors.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.PublisherId = new SelectList(_context.Publishers.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.CategoryId = new SelectList(_context.Categories.OrderBy(n => n.Name).ToList(), "Id", "Name");
			ViewBag.Url = book.ImageURL;
			return View(book);
		}

		// POST: Books/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,ImageURL, PublishingYear,CategoryId,AuthorId,PublisherId")] Book book)
		{
			if (id != book.Id)
			{
				return NotFound();
			}

			if (!ModelState.IsValid)
			{
				try
				{
					_context.Update(book);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!BookExists(book.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewBag.AuthorId = new SelectList(_context.Authors.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.PublisherId = new SelectList(_context.Publishers.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.CategoryId = new SelectList(_context.Categories.OrderBy(n => n.Name).ToList(), "Id", "Name");
			return View(book);
		}

		// GET: Books/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Books == null)
			{
				return NotFound();
			}

			var book = await _context.Books
				.Include(b => b.Author)
				.Include(b => b.Publisher)
				.Include(b => b.Category)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (book == null)
			{
				return NotFound();
			}

			return View(book);
		}

		// POST: Books/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Books == null)
			{
				return Problem("Entity set 'AppDbContext.Books'  is null.");
			}
			var book = await _context.Books.FindAsync(id);
			if (book != null)
			{
				_context.Books.Remove(book);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool BookExists(int id)
		{
			return _context.Books.Any(e => e.Id == id);
		}
	}
}

BookSeller/Views/Authors/Create.cshtml
@model BookSeller.Models.Author

@{
    ViewData["Title"] = "Create";
}

<div class="row text">
    <div class="col-md-6 offset-2">
        <p>
            <h1>
                Thêm tác giả mới
            </h1>
        </p>
        <div class="row">
            <div class="col-md-12 offset-2">
                <form asp-action="Create" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    @*<div class="col-form-label text-xl-center">
                        <img id="ProfilePicturePreview" />
                    </div>*@
                    <div class="col-form-label">
                        <label asp-for="PictureFile" class="control-label"></label>
                        <input asp-for="PictureFile" accept="image/*" />
                        <span asp-validation-for="PictureFile" class="text-danger"></span>
                    </div>
                    <div class="col-form-label">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="col-form-label">
                        <label asp-for="Bio" class="control-label"></label>
                        <textarea asp-for="Bio" class="form-control"></textarea>
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="form-group float-end">
                        <input type="submit" value="Create" class="btn btn-success" />
                        <a class="btn btn-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @*<script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $('#PictureFile').val();
        })

        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>*@
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

BookSeller/Views/Authors/Delete.cshtml
@model BookSeller.Models.Author

@{
    ViewData["Title"] = "Delete";
}

<div class="row text">
	<div class="col-md-8 offset-2">
		<p>
			<h1>
				Xoá thông tin của tác giả @Model.FullName
			</h1>
		</p>
		<div class="row">
			<div class="col-md-8 offset-2">
				<div class="col-form-label text-center">
					<img  src="@("/Img/Author/"+Model.ProfilePictureURL)"
						 alt="@Model.FullName" style="max-width:350px" />
				</div>
				<div class="col-form-label">
					<label asp-for="FullName" class="control-label"></label>
					<input asp-for="FullName" class="form-control" readonly />
					<span asp-validation-for="FullName" class="text-danger"></span>
				</div>
				<div class="col-form-label">
					<label asp-for="Bio" class="control-label"></label>
					<input asp-for="Bio" class="form-control" readonly />
					<span asp-validation-for="Bio" class="text-danger"></span>
				</div>

				<div class="form-group">
					<form asp-action="Delete">
						<input type="hidden" asp-for="Id">
						<input type="submit" value="Confirm" class="btn btn-danger float-end" />
					</form>

					<a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
				</div>

			</div>
		</div>
	</div>
</div>

BookSeller/Views/Authors/Details.cshtml
@model BookSeller.Models.Author

@{
	ViewData["Title"] = "Details";
}

<h1>Giới thiệu tác giả</h1>

<div>
	<h4>@Model.FullName</h4>
	<hr />
	<div class="row">

		<table class="table">

			<tr>
				<td width="500px">
					<div class="col-form-label">
						<img src="@("/Img/Author/"+Model.ProfilePictureURL)"
							 alt="@Model.FullName" style="max-width:350px" />
					</div>
				</td>
				<td>
					<div class="text-lg-start">
						<p>
							@Model.Bio
						</p>
					</div>
				</td>
			</tr>
			
				
			
		</table>
		<div>
			<h4>Tác phẩm tiêu biểu</h4>
			@foreach (Book item in ViewBag.bookAuthor)
			{ <a asp-controller="Books" asp-action="Details" asp-route-id="@item.Id">
				<img src="@("/Img/Book/"+item.ImageURL)" alt="@item.Name" style="max-width:120px;margin:20px;border:solid #000" />
			  </a>
			}
		</div>
		<div>
			@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
			{
				<a class="btn btn-success float-end" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
			}
 
			<a class="btn btn-primary" asp-controller="Books" asp-action="Index">Back to List</a>
		</div>
	</div>
</div>

</div>
	

BookSeller/Views/Authors/Edit.cshtml
@model BookSeller.Models.Author

@{
	ViewData["Title"] = "Edit";
}

<div class="row text">
	<div class="col-md-6 offset-2">
		<p>
		<h1>
			Chỉnh sửa thông tin tác giả @Model.FullName
		</h1>
		</p>
		<div class="row">
			<div class="col-md-12 offset-2">
				<form asp-action="Edit" enctype="multipart/form-data">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<input type="hidden" asp-for="Id" />
					<div class="col-form-label">
						<label asp-for="PictureFile" class="control-label"></label>
						<input asp-for="PictureFile" accept="image/*" />
						<span asp-validation-for="PictureFile" class="text-danger"></span>
					</div>
					<div class="col-form-label">
						<label asp-for="FullName" class="control-label"></label>
						<input asp-for="FullName" class="form-control" />
						<span asp-validation-for="FullName" class="text-danger"></span>
					</div>
					<div class="col-form-label">
						<label asp-for="Bio" class="control-label"></label>
						<textarea asp-for="Bio" class="form-control"></textarea>
						<span asp-validation-for="Bio" class="text-danger"></span>
					</div>
					<div class="form-group">
						<input type="submit" value="Save" class="btn btn-success float-end" />
						<a class="btn btn-secondary" asp-action="Index">Show All</a>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
	}

BookSeller/Views/Authors/Index.cshtml
@model IEnumerable<BookSeller.Models.Author>

@{
    ViewData["Title"] = "Index";
}

<h1>Thông tin tác giả</h1>

<div class="row">
	<div class="col-md-10 offset-md-2">
		<table class="table">
			<thead>
				<tr>
					<th>
						@Html.DisplayNameFor(model => model.ProfilePictureURL)
					</th>
					<th >
						@Html.DisplayNameFor(model => model.FullName)
					</th>
					@if (User.Identity.IsAuthenticated && User.IsInRole("Admin")){
					<th>Action</th>
					}
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td class="align-middle">
							<img class="rounded-circle" src="@("/Img/Author/"+item.ProfilePictureURL)"
							 alt="@item.FullName" style="max-width:150px" />
						</td>
						<td class="align-middle ">
							@Html.DisplayFor(modelItem => item.FullName)						
						</td>
						@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
						{
							<td class="align-middle ">
								<a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">
									<i class="bi bi-pencil-square"></i> &nbsp;Edit
								</a> |
								<a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">
									<i class="bi bi-eye"></i> &nbsp;Details
								</a> |
								<a id="@item.Id" onclick="toDelete(this)" class="btn btn-danger">
									<i class="bi bi-x-square-fill"></i> &nbsp;Delete
								</a>
							</td>
						}
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>
@section Scripts{
	<script>
		function toDelete(element) {
			let choice = confirm("Bạn có muốn xoá?")
			if (choice == true) {
				var url = '@Url.Action("DeleteConfirmed", "Authors")?id=' + element.id;
				window.location.href = url;
			}
		}

	</script>
}
@await Html.PartialAsync("_CreateItem", "Authors")