BookSeller/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookSeller.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }
        public string UserId { get; set; }
        [ForeignKey(nameof(UserId))]
        public ApplicationUser User { get; set; }

        [Display(Name = "Tên người nhận")]
        [Required(ErrorMessage = "Không được để trống tên người nhận")]
        public string Name { get; set; }


        [Display(Name = "SĐT người nhận")]
        [Required(ErrorMessage = "Không được để trống SĐT")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Địa chỉ người nhận")]
        [Required(ErrorMessage = "Không được để trống địa chỉ người nhận")]
        public string Address { get; set; }

        public int Status { get; set; }
        public DateTime OrderDate { get; set; }

        public List<OrderItem> OrderItems { get; set; }

        public static implicit operator Order(Task<Order?> v)
        {
            throw new NotImplementedException();
        }
    }
}

BookSeller/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookSeller.Data;
using BookSeller.Models;
using Microsoft.AspNetCore.Hosting;
using NuGet.Protocol;
using Microsoft.AspNetCore.Authorization;
using BookSeller.Data.Static;

namespace BookSeller.Controllers
{
	[Authorize(Roles = UserRoles.Admin)]
	public class BooksController : Controller
	{
		private readonly AppDbContext _context;
		private readonly IWebHostEnvironment _webHostEnvironment;
		public BooksController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
		{
			_context = context;
			_webHostEnvironment = webHostEnvironment;
		}
		[AllowAnonymous]

		// GET: Books
		public async Task<IActionResult> Index()
		{
			TempData["Cate"] = 0;
			var appDbContext = _context.Books.Include(b => b.Author).Include(b => b.Publisher).Include(b => b.Category);
			return View(await appDbContext.ToListAsync());
		}
		[AllowAnonymous]

		public IActionResult Filter(string searchString)
		{
			var allBooks = from b in _context.Books.Include(b => b.Author).Include(b => b.Publisher).Include(b => b.Category) select b;
			if (!string.IsNullOrEmpty(searchString))
			{
				var filterBooks = allBooks.Where(s => s.Name.Contains(searchString) || s.Author.FullName.Contains(searchString)).ToList();
				if (filterBooks.Count == 0)
				{
					ViewBag.emty = "Không tìm thấy cuốn sách này";
				}
				return View("Index", filterBooks);
			}
			return View("Index", allBooks.ToList());
		}

		[AllowAnonymous]
		public IActionResult Category(int category)
		{
			var allBooks = from b in _context.Books.Include(b => b.Author).Include(b => b.Publisher).Include(b => b.Category) select b;
			var filterBooks = allBooks.Where(s => ((int)s.CategoryId) == category).ToList();
			if(filterBooks.Count == 0)
			{
				ViewBag.emtyCate = "Không có thể loại bạn vừa tìm";
			}
			TempData["Cate"] = category;
			return View("Index", filterBooks);
		}
		[AllowAnonymous]

		// GET: Books/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Books == null)
			{
				return NotFound();
			}

			var book = await _context.Books
				.Include(b => b.Author)
				.Include(b => b.Publisher)
				.Include(b => b.Category)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (book == null)
			{
				return NotFound();
			}
			var bookPublishers = _context.Books.Where(n => n.Id != book.Id).Where(n => n.AuthorId == book.AuthorId).Take(5);
			ViewBag.bookPublisher = bookPublishers.Count() != 0 ? bookPublishers : null;
			var bookAuthors = _context.Books.Where(n => n.Id != book.Id).Where(n => n.PublisherId == book.PublisherId).Take(5);
			ViewBag.bookAuthor = bookAuthors.Count() != 0 ? bookAuthors : null;
			var bookCates = _context.Books.Where(n => n.CategoryId == book.CategoryId).Where(n => n.Id != book.Id).Take(5);
			ViewBag.bookCate = bookCates.Count() != 0 ? bookCates : null;
			return View(book);
		}
		// GET: Books/Create
		public IActionResult Create()
		{
			ViewBag.AuthorId = new SelectList(_context.Authors.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.PublisherId = new SelectList(_context.Publishers.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.CategoryId = new SelectList(_context.Categories.OrderBy(n => n.Name).ToList(), "Id", "Name");
			return View();
		}

		// POST: Books/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,PictureFile,PublishingYear,CategoryId,AuthorId,PublisherId")] Book book)
		{
			if (!ModelState.IsValid)
			{
				string wwwRootPath = _webHostEnvironment.WebRootPath;
				string fileName = Path.GetFileNameWithoutExtension(book.PictureFile.FileName);
				string extension = Path.GetExtension(book.PictureFile.FileName);
				fileName += DateTime.Now.ToString("ddMMyyyy") + extension;
				book.ImageURL = fileName;
				string path = Path.Combine(wwwRootPath + "/Img/Book", fileName);
				using (var fileStream = new FileStream(path, FileMode.Create))
				{
					await book.PictureFile.CopyToAsync(fileStream);
				}
				_context.Add(book);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			ViewBag.AuthorId = new SelectList(_context.Authors.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.PublisherId = new SelectList(_context.Publishers.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.CategoryId = new SelectList(_context.Categories.OrderBy(n => n.Name).ToList(), "Id", "Name");
			return View(book);
		}

		// GET: Books/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Books == null)
			{
				return NotFound();
			}

			var book = await _context.Books.FindAsync(id);
			if (book == null)
			{
				return NotFound();
			}
			ViewBag.AuthorId = new SelectList(_context.Authors.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.PublisherId = new SelectList(_context.Publishers.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.CategoryId = new SelectList(_context.Categories.OrderBy(n => n.Name).ToList(), "Id", "Name");
			ViewBag.Url = book.ImageURL;
			return View(book);
		}

		// POST: Books/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,ImageURL, PublishingYear,CategoryId,AuthorId,PublisherId")] Book book)
		{
			if (id != book.Id)
			{
				return NotFound();
			}

			if (!ModelState.IsValid)
			{
				try
				{
					_context.Update(book);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!BookExists(book.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewBag.AuthorId = new SelectList(_context.Authors.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.PublisherId = new SelectList(_context.Publishers.OrderBy(n => n.FullName).ToList(), "Id", "FullName");
			ViewBag.CategoryId = new SelectList(_context.Categories.OrderBy(n => n.Name).ToList(), "Id", "Name");
			return View(book);
		}

		// GET: Books/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Books == null)
			{
				return NotFound();
			}

			var book = await _context.Books
				.Include(b => b.Author)
				.Include(b => b.Publisher)
				.Include(b => b.Category)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (book == null)
			{
				return NotFound();
			}

			return View(book);
		}

		// POST: Books/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Books == null)
			{
				return Problem("Entity set 'AppDbContext.Books'  is null.");
			}
			var book = await _context.Books.FindAsync(id);
			if (book != null)
			{
				_context.Books.Remove(book);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool BookExists(int id)
		{
			return _context.Books.Any(e => e.Id == id);
		}
	}
}

BookSeller/Controllers/OrdersController.cs
using BookSeller.Data;
using BookSeller.Models;
using BookSeller.Data.Cart;
using BookSeller.Data.Service;
using BookSeller.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Drawing.Printing;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using BookSeller.Data.Static;

namespace BookSeller.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _orderService;       
        public OrdersController(ShoppingCart shoppingCart, AppDbContext context, IOrderService orderService)
        {
            _shoppingCart = shoppingCart;
            _context = context;
            _orderService = orderService;          
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var order = await _orderService.GetOrderByUserIdAndRoleAsync(userId,userRole);
            return View(order);
        }
        public async Task<IActionResult> OrderComfirmed()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var order = await _orderService.GetComfirmedOrderByUserIdAndRoleAsync(userId, userRole);
            return View(order);
        }
        public async Task<IActionResult> OrderDelete()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var order = await _orderService.GetDeleteOrderByUserIdAndRoleAsync(userId, userRole);
            return View(order);
        }
        public IActionResult ShoppingCart()
        {
            var item = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = item;
            var response = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),
            };
            return View(response);
        }
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _context.Books
                .Include(b => b.Author)
                .Include(b => b.Publisher)
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if(item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _context.Books
                .Include(b => b.Author)
                .Include(b => b.Publisher)
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder(string name, string address, string phone)
        {
            if(string.IsNullOrEmpty(name) || string.IsNullOrEmpty(address)|| string.IsNullOrEmpty(phone)){
               return RedirectToAction(nameof(Checkout));
            }
            var item = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string Name = name;
            string PhoneNumber = phone;
            string Address = address;
            await _orderService.StoreOrderAsync(item, userId, Name, PhoneNumber, Address);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");           
        }
        public async Task<IActionResult> Checkout()
        {
            ViewBag.shoppingCart = _shoppingCart.GetShoppingCartItems();
            if (_shoppingCart.GetShoppingCartTotal() == 0)
            {
				TempData["Error"] = "Giỏ hàng trống!!!";
                return RedirectToAction(nameof(ShoppingCart));
			}
            ViewBag.Total = _shoppingCart.GetShoppingCartTotal();
            return View();
        }
        public async Task<IActionResult> Details(int id)
        {
            var order = await _orderService.GetOrderByIdAsync(id);
            if(order == null)
            {
                return NotFound();
            }
            return View(order);
        }
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> ChangeStt(int OrderId,int stt)
        {
            await _orderService.ChageOrderStatus(OrderId, stt);           
            return RedirectToAction(nameof(Index));
        }
    }
}

BookSeller/Views/Orders/Checkout.cshtml
@model Order

@{
	ViewData["Title"] = "Check out";
}

<div class="row">
	<div class="col-md-8 offset-2">
		<p>
			<h4>
				Nhập thông tin thanh toán
			</h4>
		</p>

		<div class="row">
			<div class="col-md-8 offset-2">
				<div class="row">
					<div class="col-md-6">
						Tổng tiền thanh toán: @ViewBag.Total VNĐ
					</div>
					<div class="col-md-6">
						<form asp-action="CompleteOrder" name="thongtin">
						
							<div class="form-group">
								<label asp-for="Name" class="col-form-label"></label>
								<input name="Name" asp-for="Name" class="form-control" />
								<span asp-validation-for="Name" class="text-danger"></span>
							</div>
							<div class="form-group">
								<label asp-for="PhoneNumber" class="col-form-label"></label>
								<input name="Phone" asp-for="PhoneNumber" class="form-control" />
								<span asp-validation-for="PhoneNumber" class="text-danger"></span>
							</div>
							<div class="form-group">
								<label asp-for="Address" class="col-form-label"></label>
								<input name="Address" asp-for="Address" class="form-control" />
								<span asp-validation-for="Address" class="text-danger"></span>
							</div>
							<div class="form-group mt-2">
								<input type="submit" value="Thanh Toán" class="btn btn-success float-end" />
								<a class="btn btn-outline-secondary" asp-action="ShoppingCart"><i class="bi bi-arrow-return-left"></i>Giỏ hàng</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div> 
</div>
@section Scripts{
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
	<script src="https://www.paypalobjects.com/api/checkout.js"></script>

	<script>

		let _total = @Html.Raw(Math.Round(ViewBag.Total/23250,2));

		paypal.Button.render({
			//Configure environment
			env: 'sandbox',
			client: {
				sandbox: 'AcKRtgL4i68EZ2ZYuYUx3ilihAg2YhL5dtF_m19A8MjBWVOn6ewNS4M_uV8gA3xi98zTcUq38gUHbVFx'
			},

			//Customize button
			locale: 'en_US',
			style: {
				size: 'small',
				color: 'gold',
				shape: 'pill'
			},
			commit: true,

			//Set up a payment
			payment: function (data, actions) {
				return actions.payment.create({
					transactions: [{
						amount: {
							total: _total,
							currency: 'USD'
						}
					}]
				});
			},
			//Execute the payment
			onAuthorize: function (data, actions) {
				console.log(document.thongtin.Name.value)
				return actions.payment.execute().then(function () {
					if (document.thongtin.Name.value == "" || document.thongtin.Phone.value=="" || document.thongtin.Address.value==""){
						alert("Vui long nhap thong tin giao hang")
					}
					else {var url = '@Url.Action("CompleteOrder", "Orders")?name=' + document.thongtin.Name.value + '&phone=' + document.thongtin.Phone.value + '&address=' + document.thongtin.Address.value;
					window.location.href = url;}
				});
			}
		}, '#paypal-btn')
	</script>
}

BookSeller/Views/Orders/Details.cshtml
@model Order
@{
	ViewData["Title"] = "Chi tiết";
}
<div class="row">
	<div class="col-md-8 offset-2 ">
		<p>
			<h4>Chi tiết Order</h4>
			<h5>Ngày đặt hàng: @Model.OrderDate.ToString("dd/MM/yyyy")</h5>
			@if(Model.Status ==1){
		    <h5>Trạng thái đơn hàng:</h5>
			<h5 class="text-success">Đã Xác nhận và gửi đi</h5>
			}
			else if (Model.Status == -1)
			{
				<h5>Trạng thái đơn hàng:</h5>
				<h5 class="text-danger">Đã huỷ</h5>
			}else{
				<h5>Trạng thái đơn hàng:</h5>
				<h5 class="text-primary">Đang chờ</h5>
			}
		</p>

		<table class="table">
			<thead>
				<tr>
					<th>Order ID</th>
					<th>Tên sách</th>
					<th>Tổng thanh toán</th>
				</tr>
			</thead>
			<tbody>

				<tr>
					<td class="align-middle"> @Model.Id</td>
					<td class="align-middle">
						<ul style="list-style-type:none">
							@foreach (var item in @Model.OrderItems)
							{
								<li>
									<div class="alert alert-info" role="alert">
										<span class="badge bg-success">@item.Amount</span> [@item.Price.ToString()] - @item.Book.Name
									</div>
								</li>
							}
						</ul>
					</td>
					<td class="align-middle">
						@Model.OrderItems.Select(m => m.Book.Price * m.Amount).Sum().ToString()
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div class="col-md-3 offset-2">
	<p>
		<h5>Thông tin người nhận</h5>
	</p>
	<table class="table">
		<tbody>
			<tr>
				<td class="align-middle"> Tên người nhận </td>
				<td class="align-middle"> @Model.Name </td>
			</tr>
			<tr>
				<td class="align-middle"> Địa chỉ</td>
				<td class="align-middle"> @Model.Address </td>
			</tr>
			<tr>
				<td class="align-middle"> SĐT người nhận </td>
				<td class="align-middle"> @Model.PhoneNumber </td>
			</tr>
		</tbody>
	</table>
</div>
	<div class="align-middle">

		@if (Model.Status == 0)
		{
			<a asp-action="ChangeStt" asp-route-OrderId="@Model.Id" asp-route-stt="1" class="btn btn-success">
				<i class="bi bi-pencil-square"></i> &nbsp;Xác Nhận
			</a>
			<a asp-action="ChangeStt" asp-route-OrderId="@Model.Id" asp-route-stt="-1" class="btn btn-danger">
				<i class="bi bi-pencil-square"></i> &nbsp;Huỷ
			</a>
		}
		@if (Model.Status == -1)
		{
			<a asp-action="ChangeStt" asp-route-OrderId="@Model.Id" asp-route-stt="0" class="btn btn-primary">
				<i class="bi bi-pencil-square"></i> &nbsp;Hoàn Tác
			</a>
		}
		<div class="float-end mb-5">
			<a asp-action="Index" class="btn btn-secondary">
				<i class="bi bi-arrow-return-left"></i> &nbsp;Trở về
			</a>
		</div>
	
</div>

BookSeller/Views/Orders/Index.cshtml
@model List<Order>

@{ 
    ViewData["Title"] = "All orders";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Danh sách Order chưa xác nhận</h4>
            <a asp-action="OrderComfirmed" class="btn btn-success">
                <i class="bi bi-check2-circle"></i> &nbsp;Order đã xác nhận
            </a>
            <a asp-action="OrderDelete" class="btn btn-danger">
                <i class="bi bi-x-square"></i> &nbsp;Order đã huỷ
            </a>
        </p>

        <table class="table">
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Tên Sách</th>
                    <th>Tổng thanh toán</th>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <th>User</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model)
                {
                <tr>
                    <td class="align-middle">@order.Id</td>
                    <td class="align-middle">
                        <ul style="list-style-type:none">
                            @foreach (var item in order.OrderItems)
                            {
                                <li>
                                    <div class="alert alert-info" role="alert">
                                        <span class="badge bg-success">@item.Amount</span> [@item.Price.ToString()] - @item.Book.Name
                                    </div>
                                </li>
                            }
                        </ul>
                    </td>
                    <td class="align-middle">
                            @order.OrderItems.Select(m => m.Book.Price * m.Amount).Sum().ToString()
                    </td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <td class="align-middle"> @order.User.FullName </td>
                        <td class="align-middle">
                                <a asp-action="Details" asp-route-id="@order.Id" class="btn btn-primary">
                                    <i class="bi bi-pencil-square"></i> &nbsp;Detail
                                </a>
                        </td>
                    }
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

BookSeller/Views/Orders/OrderComfirmed.cshtml
@model List<Order>

@{ 
    ViewData["Title"] = "All orders";
}

<div class="row">
    <div class="col-md-10 offset-1">
        <p>
            <h4>Danh sách Order đã xác nhận</h4>
            <a asp-action="Index" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp;Order mới
            </a>
            <a asp-action="OrderDelete" class="btn btn-danger">
                <i class="bi bi-x-square"></i> &nbsp;Order đã huỷ
            </a>
        </p>

        <table class="table">
            <thead>
                <tr>
                    <th colspan="2">Order ID</th>
                    <th colspan="2">Tên Sách</th>
                    <th colspan="2">Tổng thanh toán</th>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <th colspan="2">User</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model)
                {              
                <tr>
                    <td class="align-middle">@order.Id</td>
                    <td></td>
                    <td class="align-middle">
                        <ul style="list-style-type:none">
                            @foreach (var item in order.OrderItems)
                            {
                                <li>
                                    <div class="alert alert-info" role="alert">
                                        <span class="badge bg-success">@item.Amount</span> [@item.Price.ToString()] - @item.Book.Name
                                    </div>
                                </li>
                            }
                        </ul>
                    </td>
                    <td></td>
                    <td class="align-middle">
                            @order.OrderItems.Select(m => m.Book.Price * m.Amount).Sum().ToString()
                    </td>
                    <td></td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <td class="align-middle"> @order.User.FullName </td>
                        <td></td>
                        <td class="align-middle">
                                <a asp-action="Details" asp-route-id="@order.Id" class="btn btn-primary">
                                    <i class="bi bi-pencil-square"></i> &nbsp;Detail
                                </a>
                        </td>
                        <td></td>
                    }
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

BookSeller/Views/Orders/OrderCompleted.cshtml
<div class="row">
    <div class="col-md-6 offset-3 alert alert-success text-center">
        <h2>Đặt hàng thành công!</h2>
        <p>Bạn có thể kiểm tra lịch sử đặt hàng của bạn trong profile</p>
        <hr />
        <p>Thank you!</p>
        <a class="btn btn-info" asp-controller="Books" asp-action="Index">Tiếp tục mua hàng</a>
    </div>
</div>

BookSeller/Views/Orders/ShoppingCart.cshtml
@using BookSeller.Data.ViewModels;
@model ShoppingCartViewModel
@{
	ViewData["Title"] = "Shopping Cart Summary";
}

<div class="row">
	<div class="col-md-8 offset-2">
		<div class="text-center">
			<h2>Giỏ hàng của bạn </h2>
		</div>

		<table class="table">
			<thead>
				<tr>
					<th>Số Lượng</th>
					<th>Tên Sách</th>
					<th>Giá</th>
					<th>Tạm tính</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model.ShoppingCart.ShoppingCartItems)
				{
					<tr>
						<td class="align-middle">@item.Amount</td>
						<td class="align-middle">@item.Book.Name</td>
						<td class="align-middle">@item.Book.Price VNĐ</td>
						<td class="align-middle">@(item.Amount * item.Book.Price) VNĐ</td>
						<td	class="align-middle">
							<a class="btn text-danger" asp-controller="Orders" asp-action="RemoveItemFromShoppingCart"
							  asp-route-id="@item.Book.Id">
							  <i class="bi bi-cart-dash"></i>
						  </a>
						  |
							<a class="btn text-success" asp-controller="Orders" asp-action="AddItemToShoppingCart"
						   asp-route-id="@item.Book.Id">
								<i class="bi bi-cart-plus"></i>
							</a>
						</td>					
					</tr>
				}
			</tbody>
			<tfoot>
				<tr>
					<td colspan="2"></td>
					<td><b>Tổng thanh toán:</b></td>
					<td>
						@Model.ShoppingCartTotal VNĐ
					</td>
					<td></td>
				</tr>
			</tfoot>
		</table>
		<div class="text-center">
			<div class="btn-group">
				<a
					class="btn btn-primary" asp-action="Checkout">
					Thanh Toán
				</a>
				<a class="btn btn-success" asp-controller="Books" asp-action="Index">
					Thêm mới
				</a>
			</div>
		</div>
	</div>
</div>

@if (TempData["error"] != null)
{
	<div class="col-md-6 offset-3 mt-2 alert alert-danger text-center">
		<h2>Giỏ hàng trống!</h2>
	</div>
}